# Generated by Django 3.2 on 2023-08-19 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0004_create_updated_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Bid_now', models.CharField(max_length=100)),
                ('Bid_future', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('Artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.create')),
            ],
        ),
    ]
