# Generated by Django 3.2 on 2023-08-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_password_post_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
