# Generated by Django 3.2 on 2023-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_category_options'),
        ('store', '0005_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='web.Category'),
        ),
    ]
