# Generated by Django 3.2 on 2023-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_details',
            field=models.ImageField(null=True, upload_to='store/details/'),
        ),
    ]
