# Generated by Django 3.2 on 2023-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_collection_category'),
        ('store', '0007_post_image_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='collection',
            field=models.ManyToManyField(to='web.Collection'),
        ),
    ]
