# Generated by Django 3.2 on 2023-08-21 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_post_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Family', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('National_ID', models.IntegerField()),
                ('Followers', models.IntegerField()),
                ('income', models.FloatField()),
                ('age_category', models.CharField(choices=[('adult', 'adult'), ('teenager', 'teenager'), ('child', 'child')], default='adult', max_length=255)),
                ('posts', models.ManyToManyField(to='store.Post')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
