# Generated by Django 3.2 on 2023-08-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20230822_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BidDetails',
            new_name='BidDetail',
        ),
    ]
