# Generated by Django 3.2 on 2023-08-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_biddetails_biddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddetail',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.post'),
        ),
    ]
