# Generated by Django 3.2 on 2023-08-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_biddetail_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='customer_bid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BidDetail',
        ),
    ]
