# Generated by Django 3.2 on 2023-08-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20230823_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='customer_bid',
        ),
        migrations.CreateModel(
            name='BidDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_bid', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.post')),
            ],
        ),
    ]
