# Generated by Django 3.2 on 2023-08-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_biddetail_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddetail',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.post'),
        ),
    ]
