# Generated by Django 3.2 on 2023-08-19 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create',
            options={'ordering': ['-created_time'], 'verbose_name': 'توکن', 'verbose_name_plural': 'توکن ها'},
        ),
        migrations.AddField(
            model_name='create',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
