# Generated by Django 3.2 on 2023-08-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230819_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create',
            name='updated_time',
        ),
    ]
