# Generated by Django 3.2 on 2023-08-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_create_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
