# Generated by Django 3.2 on 2023-08-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_collection_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='category',
        ),
    ]
