# Generated by Django 3.2 on 2023-08-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_collection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='store/Category'),
            preserve_default=False,
        ),
    ]
