# Generated by Django 3.2 on 2023-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='hot',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(null=True, upload_to='collection/'),
        ),
    ]
