# Generated by Django 3.2 on 2023-08-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20230820_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='hot',
            field=models.BooleanField(null=True),
        ),
    ]
