# Generated by Django 3.2 on 2023-08-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_collection_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='discription',
            field=models.CharField(max_length=255),
        ),
    ]
